In [3]:
import pandas as pd

lst = [1,2,3,4,5]
lst1 = ["A","B","c","j","p"]
df = pd.DataFrame(lst)
df1 = pd.DataFrame(lst1)
df
df1

   0
0  A
1  B
2  c
3  j
4  p

In [10]:
temp = pd.Series(
    [22, 24, 19, 25, 28, 30, 27],
    index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
)

temp

Mon    22
Tue    24
Wed    19
Thu    25
Fri    28
Sat    30
Sun    27
dtype: int64

In [11]:
data = {
    'Name': ['Alice', 'Bob', 'Carol', 'David', 'Eve'],
    'Math_Score': [85, 92, 78, 88, 95],
    'Science_Score': [90, 85, 88, 92, 87],
    'Grade_Level': [9, 10, 11, 12, 10]
}

df_stud = pd.DataFrame(data)
df_stud

    Name  Math_Score  Science_Score  Grade_Level
0  Alice          85             90            9
1    Bob          92             85           10
2  Carol          78             88           11
3  David          88             92           12
4    Eve          95             87           10

In [16]:
df_stud.head(3)
df_stud.tail(3)
df_stud.info()
df_stud.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           5 non-null      object
 1   Math_Score     5 non-null      int64
 2   Science_Score  5 non-null      int64
 3   Grade_Level    5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

       Math_Score  Science_Score  Grade_Level
count    5.000000       5.000000     5.000000
mean    87.600000      88.400000    10.400000
std      6.580274       2.701851     1.140175
min     78.000000      85.000000     9.000000
25%     85.000000      87.000000    10.000000
50%     88.000000      88.000000    10.000000
75%     92.000000      90.000000    11.000000
max     95.000000      92.000000    12.000000

In [19]:
import numpy as np
df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [10, np.nan, np.nan, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df.isnull().sum()

A    1
B    2
C    0
dtype: int64

In [24]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': ['a', 'b', 'c', 'd', 'e'],
    'C': [10, 20, 30, 40, 50]
}, index=['row1', 'row2', 'row3', 'row4', 'row5'])

df1
df1.loc['row3']
df1.iloc[2]
df1.loc['row2':'row4', ['A', 'C']]

      A   C
row2  2  20
row3  3  30
row4  4  40

In [25]:
df1.iloc[1:4,0:2]

      A  B
row2  2  b
row3  3  c
row4  4  d

In [27]:
df2 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Carol', 'David', 'Eve'],
    'Math_Score': [85, 92, 78, 88, 95],
    'Science_Score': [90, 85, 88, 92, 87],
    'Grade_Level': [9, 10, 11, 12, 10]
})
df2.groupby('Grade_Level')['Math_Score'].mean()

Grade_Level
9     85.0
10    93.5
11    78.0
12    88.0
Name: Math_Score, dtype: float64

In [38]:
df3 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Carol', 'David', 'Eve', 'Frank'],
    'Age': [15, 16, np.nan, 17, np.nan, 15],
    'Grade_Level': [9, 10, 11, 12, 9, 9]})
df3
df3['Age'].isnull().sum()
df3['Age'] = df.groupby('Grade_Level')['Age'].transform(
    lambda x: x.fillna(x.median())
)
df3
df3.drop('Name', axis=1, inplace=True)
df3

C:\Users\anupa\PyCharmMiscProject\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

    Name   Age  Grade_Level
0  Alice  15.0            9
1    Bob  16.0           10
2  Carol   NaN           11
3  David  17.0           12
4    Eve  15.0            9
5  Frank  15.0            9

In [41]:
df = pd.DataFrame({
    'Revenue': [1500, 800, 3000, 6000, 2500, 4500, 900],
    'Region': ['North', 'South', 'East', 'North', 'South', 'West', 'North'],
    'Product_Category': ['Electronics', 'Clothing', 'Food', 'Clothing','Electronics', 'Food', 'Clothing']
})
after_filter = df[(df['Revenue'].between(1000,5000))&
            (df['Region'].isin(['North', 'South'])) &
            (df['Product_Category'] != 'Electronics')]
after_filter
df

   Revenue Region Product_Category
0     1500  North      Electronics
1      800  South         Clothing
2     3000   East             Food
3     6000  North         Clothing
4     2500  South      Electronics
5     4500   West             Food
6      900  North         Clothing

In [43]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Carol', 'David'],
    'Department': ['IT', 'HR', 'IT', 'Finance'],
    'Salary': [70000, 50000, 80000, 60000]
})
after_sort = df.sort_values(by=['Department','Salary'],ascending=[True,False])
after_sort

    Name Department  Salary
3  David    Finance   60000
1    Bob         HR   50000
2  Carol         IT   80000
0  Alice         IT   70000

In [52]:
prod = pd.DataFrame({
    'product_id': [101, 102, 103, 104],
    'product_name': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    'category': ['Electronics', 'Accessories', 'Accessories', 'Electronics']
})

sales = pd.DataFrame({
    'product_id': [101, 101, 102, 103, 105],
    'sale_date': ['2024-01-01', '2024-01-02', '2024-01-01', '2024-01-03', '2024-01-04'],
    'quantity': [2, 1, 5, 3, 2],
    'revenue': [2400, 1200, 125, 135, 60]
})
prod
sales
In_join = pd.merge(prod, sales, on='product_id',how='inner')
LF_join = pd.merge(prod, sales, on='product_id',how='left')
RG_join = pd.merge(prod, sales, on='product_id',how='right')
OT_join = pd.merge(prod, sales, on='product_id',how='outer')
In_join
LF_join
RG_join
OT_join

   product_id product_name     category   sale_date  quantity  revenue
0         101       Laptop  Electronics  2024-01-01       2.0   2400.0
1         101       Laptop  Electronics  2024-01-02       1.0   1200.0
2         102        Mouse  Accessories  2024-01-01       5.0    125.0
3         103     Keyboard  Accessories  2024-01-03       3.0    135.0
4         104      Monitor  Electronics         NaN       NaN      NaN
5         105          NaN          NaN  2024-01-04       2.0     60.0